export JASMINE_SERVER_UNIT=0
export JASMINE_SERVER_INTEGRATION=0
export JASMINE_CLIENT_UNIT=1
export JASMINE_CLIENT_INTEGRATION=0

export DEBUG=1
export VELOCITY_DEBUG=1
export VELOCITY_MIRROR_DEBUG=1
export JASMINE_PACKAGES_TO_INCLUDE_IN_UNIT_TESTS=dburles:factory
export VELOCITY_DEBUG_MIRROR=1

meteor
